name: Repository variable test

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello GithubActions it's Thursday"
        if: ${{ vars.DAY_OF_WEEKS == 'MONDAY' }} 
        run: echo "Today is ${{ vars.DAY_OF_WEEKS }}!"
        env:
          First_Name: GithubActions

    
