name: Repository variable test
on: workflow_dispatch
  
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello GithubActions it's MONDAY"
        run: echo "$Hello ${{ vars.DAY_OF_WEEKS }}!"

