name: Test Vars context test
run-name: Run vars context test
on: workflow_dispatch

jobs:
  vars-context-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello VAR_TEST"
        run: echo "$Hello ${{ vars.VARS_TEST }}"

        
